apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: db-rolebinding
  namespace: {{ .Values.global.namespace }}
subjects:
  - kind: ServiceAccount
    name: db-sa
    namespace: {{ .Values.global.namespace }}
roleRef:
  kind: Role
  name: db-role
  apiGroup: rbac.authorization.k8s.io
