apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-rolebinding
  namespace: {{ .Values.global.namespace }}
subjects:
  - kind: ServiceAccount
    name: web-sa
    namespace: {{ .Values.global.namespace }}
roleRef:
  kind: Role
  name: web-role
  apiGroup: rbac.authorization.k8s.io
