apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secret.name }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  password: {{ .Values.postgres.secret.password | b64enc }}
