apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.postgres.service.type }}
  selector:
    component: postgres
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}
