apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-fe
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: lms-fe
  template:
    metadata:
      labels:
        app: lms-fe
    spec:
      serviceAccountName: web-sa
      containers:
        - name: frontend-container
          image: {{ .Values.frontend.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
