apiVersion: v1
kind: Service
metadata:
  name: lms-fe-service
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: 80
  selector:
    app: lms-fe
