apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}

---

{{- range .Values.serviceAccounts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ . }}
  namespace: {{ $.Values.namespace }}
---
{{- end }}
