- name: Deploy LMS Helm chart
  hosts: n1
  connection: local
  gather_facts: no

  tasks:
    - name: Install Helm chart for LMS
      community.kubernetes.helm:
        name: lms
        chart_path: "../charts/lms"
        release_namespace: lms-namespace
        values_files:
          - "../charts/lms/values.yaml"
        state: present
