- name: Deploy LMS Helm chart to Kubernetes
  hosts: n1
  connection: local
  gather_facts: false
  vars:
    namespace: lms2-namespace

  tasks:
    - name: Create namespace if it doesn't exist
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ namespace }}"
        state: present

    - name: Install LMS Helm chart
      community.kubernetes.helm:
        release_name: lms
        chart_ref: ./lms_app
        release_namespace: "{{ namespace }}"
        values_files:
          - ./lms_app/values.yaml
        state: present
