- name: Deploy LMS Helm chart to Kubernetes
  hosts: n1
  connection: local
  gather_facts: no

  tasks:
    - name: Install LMS Helm chart
      community.kubernetes.helm:
        name: lms
        chart_path: "./lms_app"
        release_namespace: lms2-namespace
        values_files:
          - "./lms_app/values.yaml"
        state: present
